### ISSUE TITLE
What shot are used to reproduce the evaluation in the leaderboards?

### ISSUE THREAD

**Issue by zhimin-z** [TheoremOne/llm-benchmarker-suite#10]
Is that `zero-shot` for all the evaluation results?

**Comment by acebot712** [comment]
Yes. Zero Shot. No CoT.

**Comment by acebot712** [comment]
I am currently not maintaining it. Feel free to reach out [here](https://calendly.com/abhijoy-sar/1-on-1)  in case you need more information regarding the repo :)

**Comment by zhimin-z** [comment]
> I am currently not maintaining it. Feel free to reach out [here](https://calendly.com/abhijoy-sar/1-on-1) in case you need more information regarding the repo :)

Hope this information could be added in the documentation for reference purposes :)
